/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EarnPowerRouteImport } from './routes/earn-power'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LotteryRouteImport } from './routes/lottery'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as RigsRouteImport } from './routes/rigs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsRouteImport } from './routes/skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnPowerRoute = EarnPowerRouteImport.update({
  id: '/earn-power',
  path: '/earn-power',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LotteryRoute = LotteryRouteImport.update({
  id: '/lottery',
  path: '/lottery',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const RigsRoute = RigsRouteImport.update({
  id: '/rigs',
  path: '/rigs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/earn-power': typeof EarnPowerRoute
  '/faq': typeof FaqRoute
  '/faucet': typeof FaucetRoute
  '/games': typeof GamesRoute
  '/lottery': typeof LotteryRoute
  '/missions': typeof MissionsRoute
  '/pools': typeof PoolsRoute
  '/rigs': typeof RigsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/earn-power': typeof EarnPowerRoute
  '/faq': typeof FaqRoute
  '/faucet': typeof FaucetRoute
  '/games': typeof GamesRoute
  '/lottery': typeof LotteryRoute
  '/missions': typeof MissionsRoute
  '/pools': typeof PoolsRoute
  '/rigs': typeof RigsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/earn-power': typeof EarnPowerRoute
  '/faq': typeof FaqRoute
  '/faucet': typeof FaucetRoute
  '/games': typeof GamesRoute
  '/lottery': typeof LotteryRoute
  '/missions': typeof MissionsRoute
  '/pools': typeof PoolsRoute
  '/rigs': typeof RigsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/earn-power'
    | '/faq'
    | '/faucet'
    | '/games'
    | '/lottery'
    | '/missions'
    | '/pools'
    | '/rigs'
    | '/settings'
    | '/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/earn-power'
    | '/faq'
    | '/faucet'
    | '/games'
    | '/lottery'
    | '/missions'
    | '/pools'
    | '/rigs'
    | '/settings'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/earn-power'
    | '/faq'
    | '/faucet'
    | '/games'
    | '/lottery'
    | '/missions'
    | '/pools'
    | '/rigs'
    | '/settings'
    | '/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarnPowerRoute: typeof EarnPowerRoute
  FaqRoute: typeof FaqRoute
  FaucetRoute: typeof FaucetRoute
  GamesRoute: typeof GamesRoute
  LotteryRoute: typeof LotteryRoute
  MissionsRoute: typeof MissionsRoute
  PoolsRoute: typeof PoolsRoute
  RigsRoute: typeof RigsRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn-power': {
      id: '/earn-power'
      path: '/earn-power'
      fullPath: '/earn-power'
      preLoaderRoute: typeof EarnPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lottery': {
      id: '/lottery'
      path: '/lottery'
      fullPath: '/lottery'
      preLoaderRoute: typeof LotteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rigs': {
      id: '/rigs'
      path: '/rigs'
      fullPath: '/rigs'
      preLoaderRoute: typeof RigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarnPowerRoute: EarnPowerRoute,
  FaqRoute: FaqRoute,
  FaucetRoute: FaucetRoute,
  GamesRoute: GamesRoute,
  LotteryRoute: LotteryRoute,
  MissionsRoute: MissionsRoute,
  PoolsRoute: PoolsRoute,
  RigsRoute: RigsRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
